name: Sync Code to Gitee
on:
  schedule:
    - cron:  '0 * * * *'
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@v0.08
      with:
        src: github/renbaoshuo
        dst: gitee/renbaoshuo
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        # black_list: renbaoshuo.github.io

